package com.mycompany.cms.gui.movies;

import com.mycompany.cms.util.Connector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ikelm
 */
public class MoviePanel extends javax.swing.JPanel {

    /**
     * Creates new form MoviePanel
     */
    public MoviePanel() {
        initComponents();
        refreshTable();

    }
    
    private void refreshTable() {       
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();

            String query = "SELECT movie_id, title, rating, released, genre, duration FROM movies";

                try (PreparedStatement pstmt = con.prepareStatement(query);
                    ResultSet resultSet = pstmt.executeQuery()) {

                    DefaultTableModel model = (DefaultTableModel) jMovieTable.getModel();
                    model.setRowCount(0);

                    while (resultSet.next()) {
                    int movieId = resultSet.getInt("movie_id");
                    String title = resultSet.getString("title");
                    String rating = resultSet.getString("rating");
                    int released = resultSet.getInt("released");
                    String genre = resultSet.getString("genre");
                    int duration = resultSet.getInt("duration");

                    model.addRow(new Object[]{movieId, title, rating, released, genre, duration});
                    }
                }
            } catch (SQLException e) {
              System.out.println(e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jClearButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jSearchText = new javax.swing.JTextField();
        jMovieLabel = new javax.swing.JLabel();
        jImageHolder = new javax.swing.JPanel();
        jTitleLabel = new javax.swing.JLabel();
        jRatingLabel = new javax.swing.JLabel();
        jDateLabel = new javax.swing.JLabel();
        jGenreLabel = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jDurationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMovieTable = new javax.swing.JTable();
        jTitleText = new javax.swing.JTextField();
        jRatingText = new javax.swing.JTextField();
        jReleaseDateText = new javax.swing.JTextField();
        jGenreText = new javax.swing.JTextField();
        jDurationText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(780, 720));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jClearButton.setText("Clear");
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });

        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        jAddButton.setBackground(new java.awt.Color(153, 0, 255));
        jAddButton.setForeground(new java.awt.Color(255, 255, 255));
        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchTextActionPerformed(evt);
            }
        });

        jMovieLabel.setText("Movies");

        jImageHolder.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jImageHolderLayout = new javax.swing.GroupLayout(jImageHolder);
        jImageHolder.setLayout(jImageHolderLayout);
        jImageHolderLayout.setHorizontalGroup(
            jImageHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jImageHolderLayout.setVerticalGroup(
            jImageHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTitleLabel.setText("Title");

        jRatingLabel.setText("Rating");

        jDateLabel.setText("Release date");

        jGenreLabel.setText("Genre");

        jSearchButton.setBackground(new java.awt.Color(204, 0, 255));
        jSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jDurationLabel.setText("Duration");

        jMovieTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMovieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title ", "Rating", "Release date", "Genre", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jMovieTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jMovieTable);
        if (jMovieTable.getColumnModel().getColumnCount() > 0) {
            jMovieTable.getColumnModel().getColumn(0).setResizable(false);
            jMovieTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            jMovieTable.getColumnModel().getColumn(1).setResizable(false);
            jMovieTable.getColumnModel().getColumn(2).setResizable(false);
            jMovieTable.getColumnModel().getColumn(3).setResizable(false);
            jMovieTable.getColumnModel().getColumn(4).setResizable(false);
            jMovieTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jRatingText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatingTextActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jMovieLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateLabel)
                    .addComponent(jRatingLabel)
                    .addComponent(jTitleLabel)
                    .addComponent(jGenreLabel)
                    .addComponent(jDurationLabel)
                    .addComponent(jClearButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jUpdateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(jAddButton)
                                        .addGap(36, 36, 36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTitleText)
                                            .addComponent(jRatingText)
                                            .addComponent(jReleaseDateText)
                                            .addComponent(jGenreText)
                                            .addComponent(jDurationText, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jMovieLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTitleLabel)
                                .addComponent(jTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRatingLabel)
                            .addComponent(jRatingText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateLabel)
                            .addComponent(jReleaseDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGenreLabel)
                            .addComponent(jGenreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDurationLabel)
                            .addComponent(jDurationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUpdateButton)
                            .addComponent(jAddButton)
                            .addComponent(jClearButton))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(186, 186, 186))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        // TODO add your handling code here:
                
        //CLEAR//
        
        jTitleText.setText("");
	jRatingText.setText("");
	jReleaseDateText.setText("");
	jGenreText.setText("");
	jDurationText.setText("");
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        // TODO add your handling code here:
        
        //UPDATE//
        
        String title = jTitleText.getText();
        String rating = jRatingText.getText();
        int released = Integer.parseInt((jReleaseDateText.getText()));
        String genre = jGenreText.getText();
        int duration = Integer.parseInt(jDurationText.getText()); 
        
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();
            
            int selectedRow = jMovieTable.getSelectedRow();
	    int movie_id_column = 0;

	    selectedRow = jMovieTable.getSelectedRow();
 	    String movie_id = jMovieTable.getModel().getValueAt(selectedRow, movie_id_column).toString();

	    String query = "UPDATE movies SET (title = ?, rating = ?, released = ?, genre = ?, duration = ?) WHERE (movie_id = ?)";
	    PreparedStatement prepStmt = con.prepareStatement(query);
            
	    prepStmt.setString(1, title);
            prepStmt.setString(2, rating);
            prepStmt.setInt(3, released);
            prepStmt.setString(4, genre);
            prepStmt.setInt(5, duration);
            prepStmt.setString(6, movie_id);
            
            prepStmt.executeUpdate();

	    
	    } catch (SQLException e) {
            System.out.println(e);
	    }
        
        jTitleText.setText("");
	jRatingText.setText("");
	jReleaseDateText.setText("");
	jGenreText.setText("");
	jDurationText.setText("");
        
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        
        //ADD//
        
        String title = jTitleText.getText();
        String rating = jRatingText.getText();
        int released = Integer.parseInt((jReleaseDateText.getText()));
        String genre = jGenreText.getText();
        int duration = Integer.parseInt(jDurationText.getText());  
        
        String query = "INSERT INTO movies (title, rating, released, genre, duration) VALUES (?, ?, ?, ?, ?)";
        
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();
            
	    PreparedStatement prepStmt = con.prepareStatement(query);
            
	    prepStmt.setString(1, title);
            prepStmt.setString(2, rating);
            prepStmt.setInt(3, released);
            prepStmt.setString(4, genre);
            prepStmt.setInt(5, duration);
            
            prepStmt.executeUpdate();

	    
	    } catch (SQLException e) {
            System.out.println(e);
	    }
        
        jTitleText.setText("");
	jRatingText.setText("");
	jReleaseDateText.setText("");
	jGenreText.setText("");
	jDurationText.setText("");
        
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
        
        //SEARCH//
        
        String searchInput = jSearchText.getText();
        
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();

	    String query = "SELECT * FROM movies WHERE title LIKE ?";

	    PreparedStatement prepStmt = con.prepareStatement(query);
	    prepStmt.setString(1, searchInput);
            
            ResultSet resultSet = prepStmt.executeQuery();
            resultSet.next();
            
            while(resultSet.next()){
                
                String id = String.valueOf(resultSet.getInt("movie_id"));
                String title = resultSet.getString("title");
                String rating = resultSet.getString("rating");
                String release_date = resultSet.getString("release_date");
                String genre = resultSet.getString("genre");
                String duration = String.valueOf(resultSet.getInt("duration"));
                
                String tblData[] = {id, title, rating, release_date, genre, duration};
                DefaultTableModel tblModel = (DefaultTableModel)jMovieTable.getModel();
                
            }
            
            
	    } catch (SQLException e) {
            System.out.println(e);
	    }
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchTextActionPerformed

    private void jRatingTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatingTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRatingTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:     
        
        try {
                 Connector connector = new Connector();
                 Connection con = connector.getConnection();

                 String query = "SELECT movie_id, title, rating, released, genre, duration FROM movies";

                 try (PreparedStatement pstmt = con.prepareStatement(query);
                      ResultSet resultSet = pstmt.executeQuery()) {

                     DefaultTableModel model = (DefaultTableModel) jMovieTable.getModel();
                     model.setRowCount(0);

                     while (resultSet.next()) {
                         int movieId = resultSet.getInt("movie_id");
                         String title = resultSet.getString("title");
                         String rating = resultSet.getString("rating");
                         int released = resultSet.getInt("released");
                         String genre = resultSet.getString("genre");
                         int duration = resultSet.getInt("duration");

                         model.addRow(new Object[]{movieId, title, rating, released, genre, duration});
                     }
                 }
             } catch (SQLException e) {
                 System.out.println(e);
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:     
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jClearButton;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JLabel jDurationLabel;
    private javax.swing.JTextField jDurationText;
    private javax.swing.JLabel jGenreLabel;
    private javax.swing.JTextField jGenreText;
    private javax.swing.JPanel jImageHolder;
    private javax.swing.JLabel jMovieLabel;
    private javax.swing.JTable jMovieTable;
    private javax.swing.JLabel jRatingLabel;
    private javax.swing.JTextField jRatingText;
    private javax.swing.JTextField jReleaseDateText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchText;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JTextField jTitleText;
    private javax.swing.JButton jUpdateButton;
    // End of variables declaration//GEN-END:variables
}
