/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cms.gui;


import com.mycompany.cms.util.Connector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gilbert
 */
public class AdminScreening extends javax.swing.JPanel {

    /**
     * Creates new form AdminScreening
     */
    
    //AdminScreening adminScreening = new AdminScreening();
    //    showPanel(adminScreening);
    
    
    public AdminScreening() {
        initComponents();
        refreshTable();
        
        
        jEditButton.setVisible(false);
        jEditButton.setEnabled(false);
        jDeleteButton.setVisible(false);
        jDeleteButton.setEnabled(false);
        
        jUpdatePanel.setVisible(false);
        jUpdateButton.setVisible(false);
        jUpdateButton.setEnabled(false);
        jCancelButton.setVisible(false);
        jCancelButton.setEnabled(false);
        
        //Populate movie selector with movies
        String[] movieList;
        movieList =  getMovies();
        jMovieDropDown.setModel(new javax.swing.DefaultComboBoxModel<>( movieList));
        jMovieUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(movieList));
        
        String[] cinemaList;
        cinemaList = getCinemas();
        jScreenDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(cinemaList));
        jScreenUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(cinemaList));
        
    }
    
    
    private String[] getMovies() {
        ArrayList<String> movies = new ArrayList<String>();
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();
            
            String query = "SELECT title FROM movies";
            
            PreparedStatement pstmt = con.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();
            
            movies.add("Select Movie");
            
            while (rs.next()) {
                movies.add(rs.getString("title"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        return movies.toArray(new String[(movies.size())]);
    }
    
    
    
    private String[] getCinemas() {
        ArrayList<String> cinemas = new ArrayList<String>();
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();
            
            String query = "SELECT name FROM cinemas";
            
            PreparedStatement pstmt = con.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();
            
            cinemas.add("Slect Screen");
            
            while (rs.next()) {
                cinemas.add(rs.getString("name"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        return cinemas.toArray(new String[(cinemas.size())]);
    }
    
    
    private void refreshTable() {
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();
            
            String query = "SELECT screening_id, movie_id, cinema_id, time_start, time_end, date, price FROM screening";
            
            try (PreparedStatement pstmt = con.prepareStatement(query);
                    ResultSet resultSet = pstmt.executeQuery()) {

                    DefaultTableModel model = (DefaultTableModel) jMovieTable.getModel();
                    model.setRowCount(0);

                    while (resultSet.next()) {
                    int screeningId = resultSet.getInt("screening_id");
                    int movieId = resultSet.getInt("movie_id");
                    int cinemaId = resultSet.getInt("cinema_id");
                    Time timeStart = resultSet.getTime("time_start");
                    Time timeEnd = resultSet.getTime("time_end");
                    Date date = resultSet.getDate("date");
                    int price = resultSet.getInt("price");

                    model.addRow(new Object[]{screeningId, movieId, cinemaId, timeStart, timeEnd, date, price});
                    }
                }
            } catch (SQLException e) {
              System.out.println(e);
              }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMovieLabel = new javax.swing.JLabel();
        jScreenLabel = new javax.swing.JLabel();
        jAddDateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMovieTable = new javax.swing.JTable();
        jSearchField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jClearAllButton = new javax.swing.JButton();
        jAddShowtimeButton = new javax.swing.JButton();
        jCinemaDateLabel = new javax.swing.JLabel();
        jMovieDropDown = new javax.swing.JComboBox<>();
        jScreenDropDown = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jEditButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jUpdatePanel = new javax.swing.JPanel();
        jMovieUpdate = new javax.swing.JComboBox<>();
        jScreenUpdate = new javax.swing.JComboBox<>();
        jShowDateUpdate = new javax.swing.JSpinner();
        jEndtime8 = new javax.swing.JLabel();
        jMovieLabelUpdate = new javax.swing.JLabel();
        jScreenLabelUpdate = new javax.swing.JLabel();
        jShowDateLabelUpdate = new javax.swing.JLabel();
        jTimeUpdate = new javax.swing.JLabel();
        jPriceUpdate = new javax.swing.JTextField();
        jPriceLabelUpdate = new javax.swing.JLabel();
        jShowDate7 = new javax.swing.JSpinner();
        jUpdateButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        jMovieLabel.setText("Movie");

        jScreenLabel.setText("Screen");

        jAddDateButton.setBackground(new java.awt.Color(239, 124, 18));
        jAddDateButton.setForeground(new java.awt.Color(255, 255, 255));
        jAddDateButton.setText("Add Date");
        jAddDateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAddDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddDateButtonActionPerformed(evt);
            }
        });

        jMovieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Movie", "Cinema", "Start", "End", "Date", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jMovieTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMovieTable.setGridColor(new java.awt.Color(0, 0, 0));
        jMovieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMovieTableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMovieTableMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jMovieTable);
        if (jMovieTable.getColumnModel().getColumnCount() > 0) {
            jMovieTable.getColumnModel().getColumn(0).setResizable(false);
            jMovieTable.getColumnModel().getColumn(1).setResizable(false);
            jMovieTable.getColumnModel().getColumn(2).setResizable(false);
            jMovieTable.getColumnModel().getColumn(3).setResizable(false);
            jMovieTable.getColumnModel().getColumn(4).setResizable(false);
            jMovieTable.getColumnModel().getColumn(5).setResizable(false);
            jMovieTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jSearchButton.setBackground(new java.awt.Color(239, 124, 18));
        jSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jClearAllButton.setBackground(new java.awt.Color(247, 196, 149));
        jClearAllButton.setText("Clear All");
        jClearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearAllButtonActionPerformed(evt);
            }
        });

        jAddShowtimeButton.setBackground(new java.awt.Color(239, 124, 18));
        jAddShowtimeButton.setForeground(new java.awt.Color(255, 255, 255));
        jAddShowtimeButton.setText("Add Showtime");
        jAddShowtimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddShowtimeButtonActionPerformed(evt);
            }
        });

        jCinemaDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        jCinemaDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCinemaDateLabel.setText("Cinema:    C                  Date:     29/11/2023");
        jCinemaDateLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCinemaDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMovieDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Movie", "Transformer", "9", "CJ7", "Avengers" }));
        jMovieDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMovieDropDownActionPerformed(evt);
            }
        });

        jScreenDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Screen", "1", "2", "3", "4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jEditButton.setBackground(new java.awt.Color(239, 124, 18));
        jEditButton.setForeground(new java.awt.Color(255, 255, 255));
        jEditButton.setText("Edit");
        jEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setBackground(new java.awt.Color(247, 196, 149));
        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jMovieUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Movie", "Transformer", "9", "CJ7", "Avengers" }));

        jScreenUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Screen", "1", "2", "3", "4" }));

        jShowDateUpdate.setModel(new javax.swing.SpinnerDateModel());
        jShowDateUpdate.setEditor(new javax.swing.JSpinner.DateEditor(jShowDateUpdate, "MM/dd/yyyy"));

        jEndtime8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEndtime8.setText("6:48 PM");
        jEndtime8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEndtime8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMovieLabelUpdate.setText("Movie");

        jScreenLabelUpdate.setText("Screen");

        jShowDateLabelUpdate.setText("Show Date");

        jTimeUpdate.setText("Time");

        jPriceLabelUpdate.setText("Price");

        jShowDate7.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));
        jShowDate7.setEditor(new javax.swing.JSpinner.DateEditor(jShowDate7, "hh:mm aa"));

        javax.swing.GroupLayout jUpdatePanelLayout = new javax.swing.GroupLayout(jUpdatePanel);
        jUpdatePanel.setLayout(jUpdatePanelLayout);
        jUpdatePanelLayout.setHorizontalGroup(
            jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jUpdatePanelLayout.createSequentialGroup()
                        .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMovieLabelUpdate)
                            .addComponent(jScreenLabelUpdate))
                        .addGap(76, 76, 76)
                        .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScreenUpdate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMovieUpdate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(jUpdatePanelLayout.createSequentialGroup()
                        .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jShowDateLabelUpdate)
                            .addComponent(jTimeUpdate)
                            .addComponent(jPriceLabelUpdate))
                        .addGap(55, 55, 55)
                        .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPriceUpdate)
                            .addGroup(jUpdatePanelLayout.createSequentialGroup()
                                .addComponent(jShowDate7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEndtime8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jShowDateUpdate)))))
        );
        jUpdatePanelLayout.setVerticalGroup(
            jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdatePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMovieUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMovieLabelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jScreenUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScreenLabelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShowDateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jShowDateLabelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jShowDate7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jTimeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jEndtime8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPriceUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPriceLabelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jUpdateButton.setBackground(new java.awt.Color(239, 124, 18));
        jUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        jCancelButton.setBackground(new java.awt.Color(247, 196, 149));
        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jClearAllButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAddShowtimeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAddDateButton)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jScreenLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScreenDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jMovieLabel)
                                            .addGap(59, 59, 59)
                                            .addComponent(jMovieDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCinemaDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jUpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jUpdateButton)
                                .addGap(18, 18, 18)
                                .addComponent(jCancelButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jEditButton)
                        .addGap(18, 18, 18)
                        .addComponent(jDeleteButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMovieDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMovieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jScreenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScreenDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jAddDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddShowtimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCinemaDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jUpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(314, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAddDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddDateButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jAddDateButtonActionPerformed

    private void jClearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAllButtonActionPerformed
        // TODO add your handling code here:
        
        jMovieDropDown.setSelectedIndex(0);
	jScreenDropDown.setSelectedIndex(0);
	
    }//GEN-LAST:event_jClearAllButtonActionPerformed

    private void jAddShowtimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddShowtimeButtonActionPerformed
        // TODO add your handling code here:
        
        
        
       /* int movie = jMovieDropDown.getSelectedIndex();
        int screen = jScreenDropDown.getSelectedIndex();
        int showDate = (Integer) jShowDate1.getValue();
        int time1 = jTimeDropDown1.getSelectedIndex();
        String endtime1 = jEndtime1.getText();
        int showDate2 = (Integer) jShowDate2.getValue();
        int time2 = jTimeDropDown2.getSelectedIndex();
        String endtime2 = jEndtime2.getText();
        int showDate3 = (Integer) jShowDate3.getValue();
        int time3 = jTimeDropDown3.getSelectedIndex();
        String endtime3 = jEndtime3.getText();
        int showDate4 = (Integer) jShowDate4.getValue();
        int time4 = jTimeDropDown4.getSelectedIndex();
        String endtime4 = jEndtime4.getText();
        
        String query = "INSERT INTO screening (movie_id, cinema_id, date, time_start, time_end, price) VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();
            
	    PreparedStatement prepStmt = con.prepareStatement(query);
            
	    prepStmt.setInt(1, movie);
            prepStmt.setInt(2, screen);
            prepStmt.setInt(3, showDate);
            prepStmt.setInt(4, time1);
            prepStmt.setString(5, endtime1);
            
            prepStmt.executeUpdate();

	    
	    } catch (SQLException e) {
            System.out.println(e);
	    }
        refreshTable();*/
       
    }//GEN-LAST:event_jAddShowtimeButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        
        try {

	    Connector connector = new Connector();
            Connection con = connector.getConnection();

	    int selectedRow = jMovieTable.getSelectedRow();
	    int movieid_column = 0;
 	    int movie_table_id = (int) jMovieTable.getModel().getValueAt(selectedRow, movieid_column);

            
            String query = "DELETE FROM screening WHERE screening_id = ?";
            
            PreparedStatement prepStmt = con.prepareStatement(query);
            prepStmt.setInt(1, movie_table_id);
            
            prepStmt.executeUpdate();

	} catch (SQLException e) {
        System.out.println(e);
	}
        refreshTable();
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jMovieTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMovieTableMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jMovieTableMouseExited

    private void jMovieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMovieTableMouseClicked
        // TODO add your handling code here:

        jEditButton.setVisible(true);
        jEditButton.setEnabled(true);
        jDeleteButton.setVisible(true);
        jDeleteButton.setEnabled(true);
    }//GEN-LAST:event_jMovieTableMouseClicked

    private void jEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditButtonActionPerformed
        // TODO add your handling code here:
        jUpdatePanel.setVisible(true);
        jUpdateButton.setVisible(true);
        jUpdateButton.setEnabled(true);
        jCancelButton.setVisible(true);
        jCancelButton.setEnabled(true);
    }//GEN-LAST:event_jEditButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
        
        String searchInput = jSearchField.getText();
        
        
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();

            String query = "SELECT screening_id, movie_id, cinema_id, time_start, time_end, date, price FROM screening WHERE screening_id LIKE ?";
            
                    PreparedStatement pstmt = con.prepareStatement(query);                    
                    pstmt.setString(1, "%" + searchInput + "%");
                    ResultSet resultSet = pstmt.executeQuery();

                    DefaultTableModel model = (DefaultTableModel) jMovieTable.getModel();
                    model.setRowCount(0);

                    while (resultSet.next()) {
                    int screeningId = resultSet.getInt("screening_id");
                    int movieId = resultSet.getInt("movie_id");
                    int cinemaId = resultSet.getInt("cinema_id");
                    Time timeStart = resultSet.getTime("time_start");
                    Time timeEnd = resultSet.getTime("time_end");
                    Date date = resultSet.getDate("date");
                    int price = resultSet.getInt("price");

                    model.addRow(new Object[]{screeningId, movieId, cinemaId, timeStart, timeEnd, date, price});
                    }

            } catch (SQLException e) {
              System.out.println(e);
            }
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        // TODO add your handling code here:
        jMovieUpdate.setSelectedIndex(0);
	jScreenUpdate.setSelectedIndex(0);
        jUpdatePanel.setVisible(false);
        jUpdateButton.setVisible(false);
        jUpdateButton.setEnabled(false);
        jCancelButton.setVisible(false);
        jCancelButton.setEnabled(false);
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        // TODO add your handling code here:
        
        String a = (String)jScreenUpdate.getSelectedItem();
        
        String chosenMovie = (String)jMovieUpdate.getSelectedItem();
        int selectedRow = jMovieTable.getSelectedRow();
	int screening_id_column = 0;
 	int screeningID = (int)jMovieTable.getModel().getValueAt(selectedRow, screening_id_column);
        int cinema_id = Integer.parseInt(a);
        Time time_start = (Time)jShowDate7.getValue();
        String time_end = jEndtime8.getText();
        Date javaDate = (Date)jShowDateUpdate.getValue();
        int price = Integer.parseInt(jPriceUpdate.getText());
        java.sql.Date date = new java.sql.Date(javaDate.getDate());
        
        try {
            Connector connector = new Connector();
            Connection con = connector.getConnection();

            String query = "UPDATE screening SET cinema_id = ?, time_start = ?, time_end = ?, date = ?, price = ? WHERE screening_id = ?";
                    
                    PreparedStatement prepStmt = con.prepareStatement(query);
                    
                    prepStmt.setInt(1, cinema_id);
                    prepStmt.setTime(2, time_start);
                    prepStmt.setString(3, time_end);
                    prepStmt.setDate(4, date);
                    prepStmt.setInt(5, price);

            } catch (SQLException e) {
              System.out.println(e);
        }
        

            try {
                Connector connector = new Connector();
                Connection con = connector.getConnection();

                String sQuery = "SELECT movie_id FROM movies WHERE title LIKE ?";

                PreparedStatement pstmt = con.prepareStatement(sQuery);
                pstmt.setString(1, "%" + chosenMovie + "%");
                ResultSet resultSet = pstmt.executeQuery();

                while (resultSet.next()) {
                int movieId = resultSet.getInt("movie_id");
                
                

                    String query = "UPDATE screening SET movie_id = ? WHERE screening_id = ?";

                    PreparedStatement prepStmt = con.prepareStatement(query);
                    prepStmt.setInt(1, movieId);
                    prepStmt.setInt(2, screeningID);

                    prepStmt.executeUpdate();
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
        
        
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jMovieDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMovieDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMovieDropDownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddDateButton;
    private javax.swing.JButton jAddShowtimeButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JLabel jCinemaDateLabel;
    private javax.swing.JButton jClearAllButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jEditButton;
    private javax.swing.JLabel jEndtime8;
    private javax.swing.JComboBox<String> jMovieDropDown;
    private javax.swing.JLabel jMovieLabel;
    private javax.swing.JLabel jMovieLabelUpdate;
    private javax.swing.JTable jMovieTable;
    private javax.swing.JComboBox<String> jMovieUpdate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPriceLabelUpdate;
    private javax.swing.JTextField jPriceUpdate;
    private javax.swing.JComboBox<String> jScreenDropDown;
    private javax.swing.JLabel jScreenLabel;
    private javax.swing.JLabel jScreenLabelUpdate;
    private javax.swing.JComboBox<String> jScreenUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JSpinner jShowDate7;
    private javax.swing.JLabel jShowDateLabelUpdate;
    private javax.swing.JSpinner jShowDateUpdate;
    private javax.swing.JLabel jTimeUpdate;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JPanel jUpdatePanel;
    // End of variables declaration//GEN-END:variables
}
